Host: olifer.org
Author: Denis Olifer
Email: denis@olifer.org
SiteTitle: Denis Olifer's Blog
TwitterHandle: d_olifer
AboutPhoto: "/assets/about/photo.jpg"
Description: Thoughts, stories and ideas
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{title} - {siteTitle}");
  }
PostSources: posts/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
LinksUseHttps: true
MirrorResources: true
EditLink: => "https://github.com/dolifer/blog/edit/master/input/" + doc.Source.GetRelativeInputPath()
GitHubCommit: => "https://github.com/dolifer/blog/commit/" + Blog.Generator.Data.GitVersion.Sha
GitHubOwner: dolifer
GitHubName: blog
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
GitHubBranch: blog-static
GoogleAnalytics: UA-21927702-3