name: Publish Blog

on:
  push:
    branches:
    - develop

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201' # SDK Version to use.
    - name: Deploy
      run: dotnet run -- deploy