name: Deploy Site
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - uses: actions/setup-dotnet@v1
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        with:
          dotnet-version: '3.1.100'
      - name: Run Statiq.Web publish
        run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}